### ISSUE TITLE
La exportul din ecranul "Desen" datele din grizi nu se exporta cum trebuie

### ISSUE THREAD

**Issue by LoredanaChitaru** [SoftulmeuRo/enpora#1]
1. Am intrat in ecranul "Lista Desene" din tabul Desene.
2. Am selectat un desen.
3. Am facut un export in ecranul "Desen".
4. Am observat ca Datele din grizii din josul paginii nu se exporta cum trebuie.
![export](https://cloud.githubusercontent.com/assets/12709407/8034348/6fbd388e-0def-11e5-8606-805c1d23c76d.jpg)

**Comment by crystyn90** [comment]
Rezolvat
