### ISSUE TITLE
La exportul din ecranul "Reiniore Desen" datele din grizi nu se exporta cum trebuie

### ISSUE THREAD

**Issue by LoredanaChitaru** [SoftulmeuRo/enpora#2]
1. Am intrat in ecranul "Lista Reinoiri Desene" din tabul Desene.
2. Am selectat un desen.
3. Am facut un export in ecranul "Reinoire Desen".
4. Am observat ca Datele din grizii din josul paginii nu se exporta cum trebuie.
![reinorir](https://cloud.githubusercontent.com/assets/12709407/8034540/496e90c2-0df1-11e5-8260-8ba3909199cf.jpg)

**Comment by crystyn90** [comment]
Rezolvat
