### ISSUE TITLE
In documentul "Anuitati" din Brevete nu se salveaza toate datele

### ISSUE THREAD

**Issue by andreicorbu** [SoftulmeuRo/enpora#3]
Pasul 1)
- Am creat un document nou in fereastra "Brevete -> Lista anuitati"  prin butonul "Adauga":

![anuitate3](https://cloud.githubusercontent.com/assets/12709454/8034630/1431ae2a-0df2-11e5-80b3-a522127f4758.PNG)

Pasul 2) 
- Am completat toate datele in documentul creat inclusiv in campul "Scadenta urmatoare".
- Am salvat cu butonul "Salveaza" din commanders.

![anuitate5](https://cloud.githubusercontent.com/assets/12709454/8034632/1a4d11aa-0df2-11e5-93ff-b2bd7ec3745d.PNG)

Pasul 3) 
- Am mai intrat inca o data pe documentul creat in "Brevete -> Lista anuitati" prim butonul "detalii":

![anuitate6](https://cloud.githubusercontent.com/assets/12709454/8034636/2370a152-0df2-11e5-8aea-325f05237120.PNG)

Pasul 4)
- Am observat ca campul "Scadenta urmatoare" nu s-a salvat:

![anuitate4](https://cloud.githubusercontent.com/assets/12709454/8034637/2b8c8f22-0df2-11e5-995f-230964e26081.PNG)

**Comment by crystyn90** [comment]
Rezolvat
