### ISSUE TITLE
In documentul "Anuitati" din Brevete exporturile nu se fac corect

### ISSUE THREAD

**Issue by andreicorbu** [SoftulmeuRo/enpora#4]
Pasul 1)
- Am creat un document nou in fereastra "Brevete -> Lista anuitati"  prin butonul "Adauga":

![anuitate3](https://cloud.githubusercontent.com/assets/12709454/8034630/1431ae2a-0df2-11e5-80b3-a522127f4758.PNG)

Pasul 2) 
- Am completat toate datele in documentul creat.
- Am salvat cu butonul "Salveaza" din commanders.
- Am incercat sa efectueze un export din butonul "Export".

![anuitate7](https://cloud.githubusercontent.com/assets/12709454/8034731/1e2bfb50-0df3-11e5-92c1-01c260886dc1.PNG)

Pasul 3)
- Am observat ca in fisierul excel creat unele date nu s-au copiat iar unele date s-au copiat in campuri diferite.
- Totodata am observat ca a aparut un camp nou care nu se regaseste in formular.

![anuitate](https://cloud.githubusercontent.com/assets/12709454/8034753/576e9ed6-0df3-11e5-8e5f-2b41041a6d53.PNG)

**Comment by crystyn90** [comment]
Rezolvat
