### ISSUE TITLE
Cand se "Copiaza" un document nu se reseteaza datele din grizi din subsolul documentului

### ISSUE THREAD

**Issue by andreicorbu** [SoftulmeuRo/enpora#5]
Pasul 1)
- Am creat un document nou in fereastra "Brevete -> Lista Modificari Juridice" cu butonul "Adauga":

![modificarijuridice](https://cloud.githubusercontent.com/assets/12709454/8035157/ca8d14a8-0df6-11e5-9282-a474047814b0.PNG)

Pasul 2)
- Am completat formularul si am salvat cu butonul "Salveaza" din commanderi:
- Am facut o copie la doumentul respectiv cu butonul "Copiaza":

![mj](https://cloud.githubusercontent.com/assets/12709454/8035196/20b73692-0df7-11e5-9863-019f73c6dece.PNG)

Pasul 3)

- Am observat in momentul cand s-a copiat documentul, in subsolul documentului grid-ul "Decizi" nu s-a resetat. Desi el imi apare completat acesta nu se salveza.

![mj2](https://cloud.githubusercontent.com/assets/12709454/8035247/8427e424-0df7-11e5-9d0e-f359165230d2.PNG)

Aceasta eroare se repeta in toate documentele din meniurile "Marci", "Brevete", "Desene"

**Comment by crystyn90** [comment]
Rezolvat.
