### ISSUE TITLE
Cand folosesc butonul "Copiaza" in fereastra "Registru corespondenta" numarul intrarii nu se modifica 

### ISSUE THREAD

**Issue by andreicorbu** [SoftulmeuRo/enpora#6]
Pasul 1)
- Am intrat in fereatra "Home -> Registru corespondenta".

![rc3](https://cloud.githubusercontent.com/assets/12709454/8036376/1909fcc8-0e00-11e5-8ff6-229c45c8ba10.PNG)

Pasul 2)
- Am creat un document nou cu butonul "Adauga".

![rc4](https://cloud.githubusercontent.com/assets/12709454/8036391/2f8716e8-0e00-11e5-90c1-305b3ca8a0e9.PNG)

Pasul 3)
- Am introdus datele in formular.
- Campul "Numar intrare" s-a setat automat "321123225" prin auto increment.
- Am creat o copie cu butonul "Copiaza"

![rc2](https://cloud.githubusercontent.com/assets/12709454/8036502/f071c2ae-0e00-11e5-904a-b04f9cc6337d.PNG)

Pasul 4)
- In copia creata am constatat ca "Numar intrare" nu a efectuat comanda de auto increment, numarul respectiv fiind acelasi cu numarul precedent.
- Numarul corect ar fi trebuit sa fie "321123226"

![rc](https://cloud.githubusercontent.com/assets/12709454/8036455/916cbb7e-0e00-11e5-897c-f3fca1b0c4b2.PNG)

**Comment by crystyn90** [comment]
Rezolvat.
